config/routes.rb
Castnotice::Application.routes.draw do
  constraints RegistrationAccountTypeConstraint do
    devise_for :users,
      path_names: { sign_up: "sign_up/:account_type" },
      controllers: {
        registrations: "registrations",
        sessions: "sessions",
        passwords: "passwords"
      }
  end

  namespace :admin do
    resources :events, except: [:show, :index] do
      resources :roles
    end
  end

  namespace :superadmin do
    resources :camps
    resources :users, only: [:index, :edit, :update]
    get "/mentors/invite", to: "mentors#invite"
    post "/mentors/send_invite", to: "mentors#send_invite"
  end

  resource :promo, only: [:create, :show], controller: "promo"

  resources :events, only: [:index]
  resources :categories, only: [:index]

  resource :membership, only: [:create, :new]
  resource :camper_registration, only: [:new, :create, :show]

  resource :accounts, only: [:edit, :update]
  resource :resume, only: [:edit, :update, :show]

  get "/r/:resume_slug" => "public_resumes#show", as: :public_resume
  get "/r/:resume_slug/print" => "public_resumes#print", as: :print_resume

  get "/search" => "search#index", as: :search

  resources :projects, except: [:new, :show, :index]
  resources :schools, except: [:new, :show, :index]
  resources :critiques, only: [:new, :create, :show, :index] do
    resource :response, only: [:create], controller: "critique_responses"
  end

  resources :headshots, except: [:show, :edit, :index]
  resources :videos, except: [:show, :update, :edit] do
    post "video_from_link", to: "videos#create_from_link", on: :collection
  end

  # Zencoder notification endpoint.
  post "/video_statuses" => "video_statuses#notify"

  get "/contact" => "contacts#new", :as => "contact"
  resource :contacts, only: [:new, :create]

  resources :messages, only: :create
  resources :conversations, only: [:index, :show, :new, :create]

  get "/dashboard" => "dashboard#show", as: :dashboard
end

app/models/event.rb
class Event < ActiveRecord::Base
  scope :region, proc { |ids| where("region_id IN (?)", ids) }
  scope :project, proc { |ids| where("project_type_id IN (?)", ids) }
  scope :union, proc { |ids| joins(:event_unions).where("event_unions.union_id IN (?)", ids) }
  scope :performance_skill, proc { |ids|
    joins(:role_performance_skills).where("role_performance_skills.performance_skill_id IN (?)", ids)
  }

  scope_accessible :region, :project, :union, :performance_skill

  validates :project_title, :region, :project_type, :unions,
  :production_location, :pay_rate, :staff, :location,
  :how_to_audition, presence: true

  belongs_to :region
  belongs_to :project_type
  belongs_to :user

  has_many :event_unions
  has_many :unions, through: :event_unions
  has_many :roles
  has_many :event_audition_dates
  has_many :role_performance_skills, through: :roles

  accepts_nested_attributes_for :event_audition_dates, allow_destroy: true
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :enforce_event_manage_permissions

  def new
    @event = current_user.events.build
    @event.event_audition_dates.build
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to page_path("calendar")
    else
      flash[:failure] = "Your event failed to save. Please try again."
      render :new
    end
  end

  def edit
    unless event
      redirect_to page_path("calendar")
    end
  end

  def update
    if event.update_attributes(event_params)
      redirect_to page_path("calendar")
    else
      render :edit
    end
  end

  def destroy
    event.destroy if event
    redirect_to page_path("calendar")
  end

  private

  def enforce_event_manage_permissions
    unless current_user && can_edit?
      redirect_to new_user_session_path
    end
  end

  def can_edit?
    current_user.admin? || current_user.mentor?
  end

  def event_params
    params.require(:event).permit(
      :project_title, :project_type_id, :region_id, :special_notes,
      :storyline, :how_to_audition, :audition_date, :location,
      :start_date, :end_date, :casting_director, :paid, :stipend,
      :staff, :pay_rate, :audition_times, :production_location,
      :user_id, union_ids: [],
      event_audition_dates_attributes: [:audition_date, :_destroy, :id]
    )
  end

  def event
    @event ||= Event.find(params[:id])
    unless current_user == @event.user || current_user.superadmin?
      flash[:notice] = "You are not allowed to edit this event."
      @event = nil
    else
      @event
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :store_location
  skip_before_action :enforce_promo_code_access

  def index
    events = Event.joins(:event_audition_dates).where(event_audition_dates: {audition_date: query_date_range})
      .select('events.* as event, event_audition_dates.audition_date as audition_date')
      .order("event_audition_dates.audition_date ASC")
      .periscope(event_params.fetch(:filters, {})).uniq

    if current_user.present?
      render json: events, meta: {member: true, admin: current_user.admin? || current_user.mentor?}
    else
      render json: events, meta: {member: false, admin: false}, each_serializer: LimitedEventSerializer
    end
  end

  private

  def query_date_range
    params[:date] ||= {}
    start_date = DateTime.parse(params[:date].fetch(:start, Time.now.in_time_zone("UTC").beginning_of_month.to_s))
    end_date = DateTime.parse(params[:date].fetch(:end, Time.now.in_time_zone("UTC").end_of_month.to_s))

    range_for(start_date, end_date.end_of_day)
  end

  def range_for(start_date, end_date)
    if end_date < 60.days.ago
      nil
    elsif start_date < 60.days.ago && end_date > 60.days.ago
      60.days.ago..end_date
    else
      start_date..end_date
    end
  end

  def event_params
    params.permit(date: [:start, :end], filters: [:age, union: [], project: [], region: [], performance_skill: []])
  end
end

app/views/admin/events/_event_audition_date_fields.html.erb
<div class="nested-fields">
  <%= f.hidden_field :id %>
  <%= f.date_select :audition_date, start_year: Time.now.year, end_year: Time.now.year + 4, with_css_classes: true %>
  <%= link_to_remove_association "remove date", f %>
</div>

app/views/admin/events/_form_fields.html.erb
<h1>Create an event</h1>
<p>Fill out the fields below to create a new calendar event. * Denotes a required field.</p>
<div class="row">
  <div class="col-sm-3">
    <%= e.label :project_title, "Name of Project"%>*
  </div>
  <div class="col-sm-9">
    <%= e.text_field :project_title %>
  </div>
</div>
<div class="row">
  <div class="col-sm-3">
    <%= e.label :project_type_id, "Project Type" %>*
  </div>
  <div class="col-sm-9">
    <%= e.select :project_type_id, for_select_by_model(ProjectType) %>
  </div>
</div>
<div class="row">
  <div class="col-sm-3">
    <%= e.label :region_id, "Region"%>*
  </div>
  <div class="col-sm-9">
    <%= e.select :region_id, for_select_by_model(Region) %>
  </div>
</div>
<div class="row">
  <div class="col-sm-3">
    <%= e.label :start_date, "Shoot/Start Date" %>*
  </div>
  <div class="col-sm-9">
    <%= e.date_select :start_date, start_year: Time.now.year, end_year: Time.now.year + 4, with_css_classes: true, include_blank: true %>
  </div>
</div>
<div class="row">
  <div class="col-sm-3">
    <%= e.label :end_date, "Production End Date" %>
  </div>
  <div class="col-sm-9">
    <%= e.date_select :end_date, start_year: Time.now.year, end_year: Time.now.year + 4, with_css_classes: true, include_blank: true %>
  </div>
</div>
<div class="row">
  <div class="col-sm-3">
    <%= e.label :union_ids, "Union" %>*
  </div>
  <div class="col-sm-9">
    <%= e.collection_check_boxes :union_ids, Union.all, :id, :name %>
  </div>
</div>
<div class="row">
  <div class="col-sm-3">
    <%= e.label :location, "Audition Location" %>*
  </div>
  <div class="col-sm-9">
    <%= e.text_field :location %>
  </div>
</div>
<div class="row">
  <div class="col-sm-3">
    <%= e.label :production_location, "Production Location" %>*
  </div>
  <div class="col-sm-9">
    <%= e.text_field :production_location %>
  </div>
</div>
<div class="row">
  <div class="col-sm-3">
    <%= e.label :casting_director, "Casting Director" %>
  </div>
  <div class="col-sm-9">
    <%= e.text_field :casting_director %>
  </div>
</div>
<div class="row">
  <div class="col-sm-3">
    <%= e.label :staff, "Staff"%>*
  </div>
  <div class="col-sm-9">
    <%= e.text_area :staff %>
  </div>
</div>
<div class="row">
  <div class="col-sm-3">
    <%= e.label :storyline, "Story" %>
  </div>
  <div class="col-sm-9">
    <%= e.text_area :storyline %>
  </div>
</div>
<div class="row">
  <div class="col-sm-3">
    <%= e.label :how_to_audition, "Audition Details" %>*
  </div>
  <div class="col-sm-9">
    <%= e.text_area :how_to_audition %>
  </div>
</div>
<div class="row">
  <div class="col-sm-3">
    <%= e.label :audition_date, "Date of Audition" %>*
  </div>
  <div class="col-sm-6" id="event_audition_dates_fields">
    <%= link_to_add_association "Add new date", e, :event_audition_dates, 'data-association-insertion-method' => :append %>
    <%= e.fields_for :event_audition_dates do |ad|  %>
      <%= render 'event_audition_date_fields', f: ad %>
    <% end %>
  </div>
</div>


<div class="row">
  <div class="col-sm-3">
    <%= e.label :audition_times, "Audition Times"%>*
  </div>
  <div class="col-sm-9">
    <%= e.text_area :audition_times %>
  </div>
</div>
<div class="row">
  <div class="col-sm-3">
    <%= e.label :paid, "Paid?" %>
  </div>
  <div class="col-sm-9">
    <%= e.check_box :paid %>
  </div>
</div>
<div class="row">
  <div class="col-sm-3">
    <%= e.label :stipend, "Stipend?" %>
  </div>
  <div class="col-sm-9">
    <%= e.check_box :stipend %>
  </div>
</div>
<div class="row">
  <div class="col-sm-3">
    <%= e.label :pay_rate, "Pay Rate"%>*
  </div>
  <div class="col-sm-9">
    <%= e.text_field :pay_rate %>
  </div>
</div>
<div class="row">
  <div class="col-sm-3">
    <%= e.label :special_notes, "Special Notes" %>
  </div>
  <div class="col-sm-9">
    <%= e.text_area :special_notes %>
  </div>
</div>

app/views/admin/events/edit.html.erb
<% if @event.errors.any? %>
<div id="error_explanation">
  <ul>  
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>  
</div>
<% end %>

<%= form_for @event, url: [:admin, @event], method: :put do |e| %>
  <%= render "form_fields", e: e %>

  <%= e.submit "Update Event", id: "update-event" %>
<% end %>

app/views/admin/events/new.html.erb
<% if @event.errors.any? %>
<div id="error_explanation">
  <ul>  
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>  
</div>
<% end %>

<%= form_for @event, url: admin_events_path do |e| %>
  <%= render "form_fields", e: e %>

  <%= e.submit "Create Event", id: "create-event" %>
<% end %>