config/routes.rb
Castnotice::Application.routes.draw do
  constraints RegistrationAccountTypeConstraint do
    devise_for :users,
      path_names: { sign_up: "sign_up/:account_type" },
      controllers: {
        registrations: "registrations",
        sessions: "sessions",
        passwords: "passwords"
      }
  end

  namespace :admin do
    resources :events, except: [:show, :index] do
      resources :roles
    end
  end

  namespace :superadmin do
    resources :camps
    resources :users, only: [:index, :edit, :update]
    get "/mentors/invite", to: "mentors#invite"
    post "/mentors/send_invite", to: "mentors#send_invite"
  end

  resource :promo, only: [:create, :show], controller: "promo"

  resources :events, only: [:index]
  resources :categories, only: [:index]

  resource :membership, only: [:create, :new]
  resource :camper_registration, only: [:new, :create, :show]

  resource :accounts, only: [:edit, :update]
  resource :resume, only: [:edit, :update, :show]

  get "/r/:resume_slug" => "public_resumes#show", as: :public_resume
  get "/r/:resume_slug/print" => "public_resumes#print", as: :print_resume

  get "/search" => "search#index", as: :search

  resources :projects, except: [:new, :show, :index]
  resources :schools, except: [:new, :show, :index]
  resources :critiques, only: [:new, :create, :show, :index] do
    resource :response, only: [:create], controller: "critique_responses"
  end

  resources :headshots, except: [:show, :edit, :index]
  resources :videos, except: [:show, :update, :edit] do
    post "video_from_link", to: "videos#create_from_link", on: :collection
  end

  # Zencoder notification endpoint.
  post "/video_statuses" => "video_statuses#notify"

  get "/contact" => "contacts#new", :as => "contact"
  resource :contacts, only: [:new, :create]

  resources :messages, only: :create
  resources :conversations, only: [:index, :show, :new, :create]

  get "/dashboard" => "dashboard#show", as: :dashboard
end

app/views/notifier/contact_us.text.erb
Castnotice message from <%= @from_name %>.

Sender's information:

Name: <%= @from_name %>
Email: <%= @from_email %>

Message:

<%= @content %>

app/views/notifier/critique_complete.html.erb
Your Critique Request has been completed please click the link provided to review.
<%= critique_url(@critique.uuid) %>

app/views/notifier/critique_request.html.erb
A Critique Request has been submitted please click the link provided to review.
<%= critique_url(@critique.uuid) %>

app/views/notifier/critique_response.html.erb
A Critique Response has been submitted please click the link provided to review.
<%= critique_url(@critique.uuid) %>

app/views/notifier/invite_campers.html.erb
<p>Hi BBT Family!!</p>
<p> Thank you for registering for the BBT Summer Intensive 2015! Are you ready for the best summer week of your life? We are!!  </p>
<p>We are thrilled to share our new CastNotice system with you. We need you to hop on over to CastNotice asap to input your student information. </p>
<p><%= link_to  'Click here', @link_to_sign_up %> to fill out your student registration form </p>

<p>As a special thank you for being a part of the BBT family, we are giving you a FREE CastNotice account. After you register, you will be able to upload your photos, videos, professionally format your resume and use CastNotice as your own free professional webpage.</p>

<strong>It is extremely important that you complete your full CastNotice profile, format your resume and upload your pictures. This will give the BBT staff and faculty the opportunity to get to know you before our intensive.</strong>

<p>Please register no later on CastNotice than May 1st!</p>
<p>Please send any questions to <%= mail_to 'workshops@broadwaybreakthru.com' %>.</p>
<p>See you this summer!</p>
<p>David, Steven & the whole BBT Crew</p>

app/views/notifier/invite_talent_mentors.html.erb
<p>Hi,</p>

<p>We would like to personally invite you to join CastNotice. To thank you we want to pay you for your time and services.</p>

<p>CastNotice is a revolutionary new internet universe created to foster talent by providing constructive critiques to acting, singing, dance and modeling videos from leading entertainment industry professionals, university, colleges and artistic institutions.</p>

<p>With CastNotice you will:</p>
<ul>
<li>Earn $150 an hour / $20 for each 6 minute critique right from your computer</li>
<li>Upload your audition notice into our casting calendar for free</li>
<li>Cast your projects or find new clients with our professionally curated talent database</li>
<li>Talent videos, pictures and resumes are all professionally filtered and packaged for pristine sharing and casting possibilities.</li>
<li>Bookmark your favorite talent in organized folders for specific projects</li>
<li>Talent is brought directly to your computer without leaving your home or office and/or scheduling an audition</li>
<li>Professional industry performance and event invitation system</li>
<li>Your casting notices are automatically matched with subscriber's personal and talent profiles and will appear on their personal calendars</li>
<li>Recruit for your university, school or organizationhere to create your account and to get started!</li>
</ul>

<p><%= link_to 'Click here', new_user_registration_url(account_type: 'mentor')%> to create your account and to get started!</p>

<p>Together we will eliminate the multiple inefficiencies within the conventional casting process, mentor aspiring performers, prepare casting candidates for your upcoming projects and be respectfully compensated for your experience, work and your time.</p>

<p>We can’t wait to work with you!</p>

<p>The CastNotice Team</p>

app/views/notifier/reset_campers_password_instructions.html.erb
<p>Hello <%= @user.email %>!</p>

<p>Welcome to CastNotice. Please click on the link below to verify your email addresses and create your password.</p>

<p><%= link_to 'Verify My Email Address', edit_password_url(@user, reset_password_token: @token) %></p>

<p> Once your email is verified you can upload your videos and photos and professionally format your resume. All BBT students ages 13 and up MUST upload a video, headshot and resume for review. </p>

<p>- The CastNotice Team </p>