config/routes.rb
Castnotice::Application.routes.draw do
  constraints RegistrationAccountTypeConstraint do
    devise_for :users,
      path_names: { sign_up: "sign_up/:account_type" },
      controllers: {
        registrations: "registrations",
        sessions: "sessions",
        passwords: "passwords"
      }
  end

  namespace :admin do
    resources :events, except: [:show, :index] do
      resources :roles
    end
  end

  namespace :superadmin do
    resources :camps
    resources :users, only: [:index, :edit, :update]
    get "/mentors/invite", to: "mentors#invite"
    post "/mentors/send_invite", to: "mentors#send_invite"
  end

  resource :promo, only: [:create, :show], controller: "promo"

  resources :events, only: [:index]
  resources :categories, only: [:index]

  resource :membership, only: [:create, :new]
  resource :camper_registration, only: [:new, :create, :show]

  resource :accounts, only: [:edit, :update]
  resource :resume, only: [:edit, :update, :show]

  get "/r/:resume_slug" => "public_resumes#show", as: :public_resume
  get "/r/:resume_slug/print" => "public_resumes#print", as: :print_resume

  get "/search" => "search#index", as: :search

  resources :projects, except: [:new, :show, :index]
  resources :schools, except: [:new, :show, :index]
  resources :critiques, only: [:new, :create, :show, :index] do
    resource :response, only: [:create], controller: "critique_responses"
  end

  resources :headshots, except: [:show, :edit, :index]
  resources :videos, except: [:show, :update, :edit] do
    post "video_from_link", to: "videos#create_from_link", on: :collection
  end

  # Zencoder notification endpoint.
  post "/video_statuses" => "video_statuses#notify"

  get "/contact" => "contacts#new", :as => "contact"
  resource :contacts, only: [:new, :create]

  resources :messages, only: :create
  resources :conversations, only: [:index, :show, :new, :create]

  get "/dashboard" => "dashboard#show", as: :dashboard
end

app/models/role.rb
class Role < ActiveRecord::Base
  AGE_MIN = 1
  AGE_MAX = 99

  belongs_to :event
  has_many :role_performance_skills
  has_many :performance_skills, through: :role_performance_skills
  validate :range_for_age

  scope :age, proc { |age| where("age_range @> ?", age.to_i) }

  def age_min=(min)
    max = self.age_range ? self.age_range.end : AGE_MAX
    self.age_range = (min.to_i..max)
  end

  def age_max=(max)
    min = self.age_range ? self.age_range.begin : AGE_MIN
    self.age_range = (min..max.to_i)
  end

  def age_min
    self.age_range ? self.age_range.begin : nil
  end

  def age_max
    self.age_range ? self.age_range.max : nil
  end

  def range_for_age
    if age_min.to_i > age_max.to_i
      errors.add(:base, "minimum age is cannot be greater than maximum age")
    end
  end
end

app/controllers/admin/roles_controller.rb
module Admin
  class RolesController < ApplicationController
    before_action do
      @event = Event.find(params[:event_id])
    end

    def index
      @roles = @event.roles
    end

    def new
      @role = @event.roles.build
    end

    def create
      @role = @event.roles.build(role_params)

      if @role.save
        redirect_to admin_event_roles_path(@event), notice: "Successfully added role"
      else
        flash[:failure] = "Sorry unable to save please correct errors:
        #{@role.errors.full_messages.to_sentence}"
        render :new
      end
    end

    def edit
      @role = @event.roles.find(params[:id])
    end

    def update
      @role = @event.roles.find(params[:id])

      if @role.update_attributes(role_params)
        redirect_to admin_event_roles_path(@event), notice: "Successfully updated role"
      else
        flash[:failure] = "Sorry unable to save please correct errors:
        #{@role.errors.full_messages.to_sentence}"
        render :edit
      end
    end

    def destroy
      @role = @event.roles.find(params[:id])
      @role.destroy

      redirect_to admin_event_roles_path(@event), notice: "Successfully deleted role"
    end

    def show
      @role = @event.roles.find(params[:id])
    end

    private

    def role_params
      params.require(:role).permit(
        :description,
        :age_min,
        :age_max,
        :gender,
        :ethnicity,
        performance_skill_ids: []
      )
    end
  end
end

app/views/admin/roles/_form.html.erb
<%= form_for [:admin, @event, @role] do |f| %>
  <div class="row">
    <div class="col-md-6">
      <%= f.label :description, "Seeking" %>
      <%= f.text_field :description %>

      <%= f.label :gender %>
      <%= f.text_field :gender %>

      <%= f.label :ethnicity %>
      <%= f.text_field :ethnicity %>

      <%= f.label :age_min, "Age Min" %>*
      <%= select_tag "role[age_min]", options_for_select((Role::AGE_MIN..Role::AGE_MAX), @role.age_min) %>

      <%= f.label :age_max, "Age Max" %>*
      <%= select_tag "role[age_max]", options_for_select((Role::AGE_MIN..Role::AGE_MAX), @role.age_max)%>
    </div>

    <div class="col-md-12">
      <h2>Skills</h2>
    </div>

    <% grouped_performance_skills.in_groups(2, false) do |skills| %>
      <div class="col-md-6">
        <% skills.each do |category, skills| %>
          <h4><%= category.titleize %></h4>
          <div>
            <%= f.collection_select :performance_skill_ids, skills, :id, :name, {}, multiple: true, "data-placeholder" => "Choose one or more options..." %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <%= f.submit "#{@role.new_record? ? "Create" : "Update" } Role" %>
  <br>
  <span class="glyphicon glyphicon-chevron-left"></span> <%= link_to "Back to Calendar", page_path("calendar") %>
<% end %>

app/views/admin/roles/edit.html.erb
<h1>Calendar Admin - Edit Role for <%= @event.project_title %></h1>
<%= render "form" %>

app/views/admin/roles/index.html.erb
<h1>Calendar Admin - Manage Roles</h1>

<span class="glyphicon glyphicon-plus mini-link"></span> <%= link_to "Add Role", new_admin_event_role_path(@event), :class => "mini-link" %>
<br><br>
<p>Current roles for <%= @event.project_title %>:</p>
<% @roles.each do |role| %>
  <div class="role">
    <h3 class="description"><%= role.description %></h3>
    <%= link_to "View", admin_event_role_path(@event, role), :class => "mini-link" %> | 
    <%= link_to "Edit", edit_admin_event_role_path(@event, role), :class => "mini-link" %> | 
    <span class="glyphicon glyphicon-trash mini-link"></span> <%= link_to "Delete", admin_event_role_path(@event, role), method: :delete, confirm: "Are you sure?", :class => "mini-link" %>
  </div>
<% end %>

app/views/admin/roles/new.html.erb
<h1>Calendar Admin - Add Role for <%= @event.project_title %></h1>
<%= render "form" %>

app/views/admin/roles/show.html.erb
<h1>Calendar Admin - View Role</h1>
<h3><%= @event.project_title %></h3>
<p>Description: <%= @role.description %></p>
<span class="glyphicon glyphicon-chevron-left"></span> <%= link_to "Back to Calendar", page_path("calendar") %>