config/routes.rb
Castnotice::Application.routes.draw do
  constraints RegistrationAccountTypeConstraint do
    devise_for :users,
      path_names: { sign_up: "sign_up/:account_type" },
      controllers: {
        registrations: "registrations",
        sessions: "sessions",
        passwords: "passwords"
      }
  end

  namespace :admin do
    resources :events, except: [:show, :index] do
      resources :roles
    end
  end

  namespace :superadmin do
    resources :camps
    resources :users, only: [:index, :edit, :update]
    get "/mentors/invite", to: "mentors#invite"
    post "/mentors/send_invite", to: "mentors#send_invite"
  end

  resource :promo, only: [:create, :show], controller: "promo"

  resources :events, only: [:index]
  resources :categories, only: [:index]

  resource :membership, only: [:create, :new]
  resource :camper_registration, only: [:new, :create, :show]

  resource :accounts, only: [:edit, :update]
  resource :resume, only: [:edit, :update, :show]

  get "/r/:resume_slug" => "public_resumes#show", as: :public_resume
  get "/r/:resume_slug/print" => "public_resumes#print", as: :print_resume

  get "/search" => "search#index", as: :search

  resources :projects, except: [:new, :show, :index]
  resources :schools, except: [:new, :show, :index]
  resources :critiques, only: [:new, :create, :show, :index] do
    resource :response, only: [:create], controller: "critique_responses"
  end

  resources :headshots, except: [:show, :edit, :index]
  resources :videos, except: [:show, :update, :edit] do
    post "video_from_link", to: "videos#create_from_link", on: :collection
  end

  # Zencoder notification endpoint.
  post "/video_statuses" => "video_statuses#notify"

  get "/contact" => "contacts#new", :as => "contact"
  resource :contacts, only: [:new, :create]

  resources :messages, only: :create
  resources :conversations, only: [:index, :show, :new, :create]

  get "/dashboard" => "dashboard#show", as: :dashboard
end

app/models/user.rb
class User < ActiveRecord::Base
  MAXIMUM_HEADSHOTS = 10
  MAXIMUM_VIDEOS = 10

  has_one :resume
  has_one :background_image, -> { where is_background: true }, class: Headshot
  has_one :mentor_bio
  has_one :camper
  has_many :received_messages, class: Message, foreign_key: :recipient_id
  has_many :sent_messages, class: Message, foreign_key: :sender_id
  has_many :unread_messages, -> { where recipient_read_at: nil }, foreign_key: :recipient_id, class: Message
  has_many :critiques

  has_many :critique_responses_given, class: CritiqueResponse
  has_many :critique_responses_received, class: CritiqueResponse, through: :critiques, source: :response
  has_many :events

  accepts_nested_attributes_for :mentor_bio

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :tos, acceptance: true, on: :create
  validates :name, :email, :birthday, presence: true
  validates :parent_name, :parent_email, :parent_location, :parent_city, :parent_state,
    :parent_zip, :parent_phone, presence: true, on: :create, if: :under_18?

  validates_presence_of :location_address, :location_city, :location_state,
    :location_zip, on: :create, if: :camper

  scope :talent_mentors, -> { where(mentor: true).order(:email) }
  scope :admins, -> { where(admin: true).order(:email) }
  scope :subscribers, -> { where(admin: false, mentor: false).order(:email) }

  def superadmin?
    email == "hello@castnotice.com" ? true : false
  end

  def happy_birthday?
    birthday.day == Date.current.day && birthday.month == Date.current.month
  end

  def under_18?
    return false unless birthday.present?
    birthday > 18.years.ago
  end

  def conversations
    Conversation.where("sender_id = ? OR recipient_id = ?", id, id)
  end

  def correspondent_in?(conversation)
    id == conversation.recipient_id || id == conversation.sender_id
  end

  def talent?
    !mentor && !admin
  end

  def can_send_messages?
    talent? || admin?
  end

  def can_send_messages_to?(recipient)
    can_send_messages? && id != recipient.id && !recipient.mentor?
  end

  def eligible_for_free_critique?
    stripe_customer.subscriptions.retrieve(stripe_plan_id).plan.id.to_sym == Stripe::Plans::BROADWAY.id &&
    critiques.where(payment_method: "breakthru_free").count == 0
  end

  def address
    [location_address, location_address_two, location_city, location_state, location_zip].select(&:present?).join(", ")
  end

  def has_membership?
    stripe_customer_id.present?
  end

  def parent_address
    [parent_location, parent_location_two, parent_city, parent_state, parent_zip].select(&:present?).join(", ")
  end

  def reset_campers_password_instructions!
    token = set_reset_password_token
    Notifier.reset_campers_password_instructions(self, token).deliver
  end

  def stripe_customer
    @stripe_customer ||= begin
      Stripe::Customer.retrieve(stripe_customer_id)
    rescue Exception => e
      raise "Unable to load stripe customer: #{e.message}"
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @mentors = User.talent_mentors
  end

  def edit
    @mentor = User.find(params[:id])
  end

  def update
    @mentor = User.find(params[:id])
    if @mentor.update_attributes(user_params)
      flash[:notice] = "Talent mentor successfully updated"
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :mentor
    )
  end
end

app/controllers/superadmin/camps_controller.rb
class Superadmin::CampsController < ApplicationController
  before_action :ensure_superadmin
  before_action :find_camp, only: [:edit, :update]

  def index
    @camps = Camp.all
    incomplete = IncompleteOrder.all(CamperRegistration.pluck(:order_id))
    @unregistered = incomplete ? incomplete.group_by(&:code) : {}
  end

  def show
    @camp = Camp.find(params[:id])
    respond_to do |format|
      format.csv { render text: @camp.to_csv }
    end
  end

  def create
    camp.attributes = camp_params
    if camp.save
      redirect_to superadmin_camps_path
    else
      render :new
    end
  end
  alias update create

  private

  def find_camp
    @camp = Camp.find(params[:id])
  end

  def camp
    @camp ||= Camp.new
  end
  helper_method :camp

  def camp_params
    params.require(:camp).permit!
  end
end

app/controllers/superadmin/mentors_controller.rb
class Superadmin::MentorsController < ApplicationController
  before_action :ensure_superadmin

  def send_invite
    email = params[:email]
    mail = Notifier.invite_talent_mentors(email)
    if mail.deliver
      flash[:success] = "Your invite has been sent."
    else
      flash[:failure] = "Your invite failed to be sent, please try again."
    end
    redirect_to superadmin_users_path
  end
end

app/controllers/superadmin/users_controller.rb
class Superadmin::UsersController < ApplicationController
  before_action :ensure_superadmin

  def index
    @account_type = params[:type]
    if @account_type == "admins"
      @users = User.admins.decorate
    elsif @account_type == "mentors"
      @users = User.talent_mentors.decorate
    else
      @users = User.subscribers.order("email").decorate
    end
  end

  def edit
    @user = User.find(params[:id]).decorate
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = "User successfully updated"
      redirect_to :back
    else
      render :edit
    end
  end

  def user_params
    params.require(:user).permit(
      :name, :email, :mentor, :admin, :location_address,
      :location_address_two, :location_city, :location_state,
      :location_zip, :parent_name, :parent_email,
      :parent_location, :parent_location_two, :parent_city,
      :parent_state, :parent_zip, :parent_phone)
  end
end

app/views/superadmin/users/edit.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li class="error"><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<h1> Edit User </h1>
<% if @user.stripe_plan %>
  <div class="plan-information">
    <h3>Plan Level: <%= @user.stripe_plan.plan.name %></h3>
  </div>
<% end %>
<%= form_for @user, url: superadmin_user_path(@user), method: :put  do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :location_address, "Address One" %>
  <%= f.text_field :location_address %>

  <%= f.label :location_address_two, "Address Two" %>
  <%= f.text_field :location_address_two %>

  <%= f.label :location_city, "City" %>
  <%= f.text_field :location_city %>

  <%= f.label :location_state, "State" %>
  <%= f.select :location_state, us_states_select, include_blank: true %>

  <%= f.label :location_zip, "Zip Code" %>
  <%= f.text_field :location_zip %>


  <%= f.label :parent_name, "Parents Fullname" %>
  <%= f.text_field :parent_name %>

  <%= f.label :parent_email, "Parents Email" %>
  <%= f.email_field :parent_email %>

  <%= f.label :parent_location, "Parents Street Address" %>
  <%= f.text_field :parent_location %>

  <%= f.label :parent_location_two, "Parents Suite/Apt" %>
  <%= f.text_field :parent_location_two %>

  <%= f.label :parent_city, "Parents City" %>
  <%= f.text_field :parent_city %>

  <%= f.label :parent_state, "Parents State" %>
  <%= f.select :parent_state, us_states_select %>

  <%= f.label :parent_zip, "Parents Zip Code" %>
  <%= f.text_field :parent_zip %>

  <%= f.label :parent_phone, "Parents Phone" %>
  <%= f.text_field :parent_phone %>

  <%= f.label :admin, "Admin?" %>
  <%= f.check_box :admin %>

  <%= f.label :mentor, "Mentor?" %>
  <%= f.check_box :mentor %>
  <fieldset>
    <%= f.submit "Save" %>
  </fieldset>
<% end %>

app/views/superadmin/users/index.html.erb
<h1> Users </h1>
<% if @account_type == "mentors" %>
  <%= link_to "Invite", superadmin_mentors_invite_path, class: "btn" %>
<% end %>

<table class="standard">
  <thead>
    <tr>
      <th>ID</th>
      <th>Email</th>
      <th>Name</th>
      <th>Birthday</th>
      <th>Stripe Customer ID</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%- @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= user.birthday %> </td>
        <td><%= user.stripe_customer_id %></td>
        <td><%= link_to "Edit", edit_superadmin_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>